package by.gstu.courses.domain;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

/**
 * createdAt: 11/23/2020
 * project: SaleCoursesServer
 *
 * Autogenerated user info. Info should exists 24h
 *
 * @author Alexander Petrushkin
 */
@Getter
@Setter
@Entity
@Table(name = "temp_users_table")
public class TempUser {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String email;
    private String login;
    private String password;

    @Column(unique = true)
    private String activationUUID;
}
