package by.gstu.courses.service;

import by.gstu.courses.model.TempUser;
import by.gstu.courses.model.User;

/**
 * createdAt: 11/24/2020
 * project: SaleCoursesServer
 *
 * @author Alexander Petrushkin
 */
public interface AuthenticateService {
    TempUser generateTempUser(String email, String code);

    /**
     * Try to find autogenerated user account, and save as
     * confirmed full-user account
     * @param code - unique UUID for temp user
     * @return saved user
     */
    User transferTempUser(String code);

    User registrationUser(User user, String code);

    void confirmVerification(String code);
}
