package by.gstu.edu.service;

import by.gstu.edu.model.TempUser;
import by.gstu.edu.model.User;

/**
 * createdAt: 11/24/2020
 * project: SaleCoursesServer
 *
 * @author Alexander Petrushkin
 */
public interface AuthenticateService {
    TempUser generateTempUser(String email);

    /**
     * Try to find autogenerated user account, and save as
     * confirmed full-user account
     * @param email - user email
     * @return saved user
     */
    User transferTempUser(String email);

    User registrationUser(User user, String code);

    void confirmVerification(String code);
}
