package by.gstu.courses.model;

import javax.persistence.*;

/**
 * createdAt: 11/23/2020
 * project: SaleCoursesServer
 *
 * Autogenerated user info. Info should exists 24h
 *
 * @author Alexander Petrushkin
 */
@Entity
@Table(name = "temp_users_table")
public class TempUser {
    private Long id;
    private String email;
    private String login;
    private String password;
    private String activationUUID;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(unique = true)
    public String getActivationUUID() {
        return activationUUID;
    }

    public void setActivationUUID(String activationUUID) {
        this.activationUUID = activationUUID;
    }
}
