package by.gstu.courses.repository;

import by.gstu.courses.domain.Permissions;
import by.gstu.courses.domain.Role;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;

/**
 * createdAt: ${DATE}
 * project: ${PROJECT_NAME}
 *
 * @author Alexander Petrushkin
 */
public interface RoleRepository extends CrudRepository<Role, String> {
    // WARN!!! native query table name generated by @CollectionTable in Role class
    // field permissions
    @Query(value = "select distinct name from permissions" , nativeQuery = true)
    Iterable<Permissions.Permission> selectAllDistinctPermissions();
    @Modifying
    @Query(value = "update User u set u.role=:toRole where u.role=:fromRole")
    int migrateFromRole(Role fromRole, Role toRole);
}
